name: flare_splash_screen
description: Facilitator for having a Splash screen with a Flare animation until some work has been done for the initialization of the app
version: 1.1.0
author: jaumard <jimmy.aumard@gmail.com>
homepage: https://github.com/jaumard/flare_splash_screen

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flare_flutter: ^1.3.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
